theme = "blowfish"
baseURL = "https://dungan24.github.io/"
defaultContentLanguage = "ko"
enableRobotsTXT = true
summaryLength = 0
buildDrafts = false
buildFuture = false
enableEmoji = true

[pagination]
  pagerSize = 20

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# markup config defined in markup.toml
