baseURL = 'https://dungan24.github.io/'
languageCode = 'ko-KR'
title = 'Market Pulse'
theme = 'PaperMod'
[pagination]
pagerSize = 10

[params]
description = '매일 업데이트되는 시장 브리핑'
defaultTheme = 'auto'
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowShareButtons = false

[params.homeInfoParams]
Title = 'Market Pulse'
Content = '매일 아침, 팩트만 담은 시장 브리핑을 전해드려요.'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/dungan24/dungan24.github.io'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[markup.goldmark.renderer]
unsafe = true
